spring:
  h2:
    console.enabled: true
  datasource:
    username: testdb
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: psw1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
